export const POST_UPLOAD_START ='POST_UPLOAD_START'
export const POST_UPLOAD_SUCCESS ='POST_UPLOAD_SUCCESS'
export const POST_UPLOAD_FAILURE ='POST_UPLOAD_FAILURE'

export const POST_TOP_START ='POST_TOP_START'
export const POST_TOP_SUCCESS ='POST_TOP_SUCCESS'
export const POST_TOP_FAILURE ='POST_TOP_FAILURE'

export const POST_DETAILS_START = 'POST_DETAILS_START'
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS'
export const POST_DETAILS_FAILURE = 'POST_DETAILS_FAILURE'

export const POST_CREATE_START ='POST_CREATE_START'
export const POST_CREATE_SUCCESS ='POST_CREATE_SUCCESS'
export const POST_CREATE_FAILURE ='POST_CREATE_FAILURE'
export const POST_CREATE_RESET ='POST_CREATE_RESET'

export const POST_EDIT_START ='POST_EDIT_START'
export const POST_EDIT_SUCCESS ='POST_EDIT_SUCCESS'
export const POST_EDIT_FAILURE ='POST_EDIT_FAILURE'
export const POST_EDIT_RESET ='POST_EDIT_RESET'

export const POST_LIKE_START ='POST_LIKE_START'
export const POST_LIKE_SUCCESS ='POST_LIKE_SUCCESS'
export const POST_LIKE_FAILURE ='POST_LIKE_FAILURE'
export const POST_LIKE_RESET ='POST_LIKE_RESET'

export const POST_COMMENT_START ='POST_COMMENT_START'
export const POST_COMMENT_SUCCESS ='POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAILURE ='POST_COMMENT_FAILURE'
export const POST_COMMENT_RESET ='POST_COMMENT_RESET'

export const POST_DELETE_START = 'POST_DELETE_START'
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS'
export const POST_DELETE_FAILURE = 'POST_DELETE_FAILURE'