export  const REGISTER_START = 'REGISTER_START'
export  const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export  const REGISTER_FAILURE = 'REGISTER_FAILURE'

export  const LOGIN_START = 'LOGIN_START'
export  const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export  const LOGIN_FAILURE = 'LOGIN_FAILURE'
export  const LOGOUT = 'LOGOUT'

export  const UPDATE_START = 'UPDATE_START'
export  const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export  const UPDATE_FAILURE = 'UPDATE_FAILURE'